name: Build and deploy container app to Azure Web App - bsvdevapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_SERVER_URL }}
        username: ${{ secrets.AzureAppService_ContainerUsername_8afd867c8fbd41b0a795bd0b1736fdcc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_044ea0ec05074407b1167e91fc9b6efd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8afd867c8fbd41b0a795bd0b1736fdcc }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bsvdevapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bfabf6e4cf9a409cbcd166759df87ec4 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_8afd867c8fbd41b0a795bd0b1736fdcc }}/appsvc/staticsite:${{ github.sha }}'
